title: "Music Information Retrieval Fundamentals: From Classic Algorithms to Deep Learning approcches"
author: "Carlos Hernandez-Olivan"
email: "carloshero@unizar.esl"
release: "1"
logo: 'logo.png'

# Short description about the book
description: >-
  Lectures for introducing MIR concepts and models to new students.
execute:
#  execute_notebooks           : auto
  execute_notebooks           : off
  timeout: -1

# HTML-specific settings
html:
  favicon              : "logo.png"
  home_page_in_navbar  : false
  use_edit_page_button : true
  use_repository_button: true
  use_issues_button    : true

# Interact link settings
notebook_interface            : "notebook"

repository:
  url           : "https://github.com/carlosholivan/MIR-book/"
  branch        : master
  path_to_book  : mir_book

# Launch button settings
#launch_buttons:
#  binder             : false
#  binderhub          : false
#  binderhub_url      : off
#  jupyterhub         : false
#  thebe              : false
#  colab              : false

# Launch button settings
launch_buttons:
#  notebook_interface: classic #jupyterlab
  binderhub_url: https://mybinder.org
#  colab_url: https://colab.research.google.com


# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
   
latex:
  latex_engine                : "pdflatex"
  use_jupyterbook_latex       : true # use jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: mir_book.tex
    
sphinx:
  config:
    html_show_copyright: false
    latex_toplevel_sectioning: 'section'
#    latex_show_urls: 'footnote'
    latex_elements.papersize: a4paper
    latex_elements.pointsize: 12pt
    

#google_analytics:
  #mytrackingcode: 